#!/bin/sh

uci -q del_list network.wan.dns='223.5.5.5' || :
uci -q add_list network.wan.dns='223.5.5.5' || exit 1
uci -q del_list network.wan.dns='119.29.29.29' || :
uci -q add_list network.wan.dns='119.29.29.29' || exit 1
