#!/bin/sh

set -e

uci -q set network.dial=interface
uci -q set network.dial.proto='pppoe'
uci -q set network.dial.device='eth0'
uci -q set network.dial.ipv6='auto'
uci -q set network.dial.norelease='1'
uci -q set network.dial.auto='0'
uci -q set network.dial.disabled='1'

for dns in 223.5.5.5 119.29.29.29; do
    case " $(uci -q get network.dial.dns) " in
        *" $dns "*) ;;
        *) uci -q add_list "network.dial.dns=$dns" ;;
    esac
done

case " $(uci -q get firewall.wan.network) " in
    *" dial "*) ;;
    *) uci -q add_list firewall.wan.network='dial' ;;
esac

# First-boot defaults are committed by OpenWrt's boot script.
[ "${1:-}" = '--defaults' ] && exit 0

uci commit network
uci commit firewall
/etc/init.d/network reload
/etc/init.d/firewall reload
