#!/bin/sh
uci set attendedsysupgrade.client.login_check_for_upgrades='0' || exit 1
uci set attendedsysupgrade.client.upgrade_packages='0' || exit 1

[ "${1:-}" = '--defaults' ] && exit 0

uci commit attendedsysupgrade || exit 1
